debugging

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -124,9 +124,10 @@ stages:
           export public_key=$(cat id_rsa.pub)
           find $(modulePath)/cluster/environments/azure-simple -type f -name '*.tf' -exec sed -i 's/github.com\/Microsoft\/bedrock\/cluster/..\/../g' {} \;
           go test -v -run TestIT_Bedrock_AzureSimple_Test -timeout 99999s | tee TestIT_Bedrock_AzureSimple_Test.log
-          failed=$?
-          echo "This is failed $failed"
+          test1=$?
           terratest_log_parser -testlog TestIT_Bedrock_AzureSimple_Test.log -outputdir single_test_output
+          test2 = $?
+          echo "Test1: $test1 Test2: $test2"
           if [ $failed -eq 0 ]
           then
             echo "Bedrock_Build_Azure_Simple: Test passed."
@@ -183,13 +184,16 @@ stages:
         export public_key=$(cat id_rsa.pub)
         find $(modulePath)/cluster/environments/azure-single-keyvault -type f -name '*.tf' -exec sed -i 's/github.com\/Microsoft\/bedrock\/cluster/..\/../g' {} \;
         go test -v -run TestIT_Bedrock_AzureCommon_KV_Test -timeout 99999s | tee TestIT_Bedrock_AzureCommon_KV_Test.log
+        test1 = $?
         terratest_log_parser -testlog TestIT_Bedrock_AzureCommon_KV_Test.log -outputdir common_test_output
-        if [ $? -eq 0 ]
-        then
-          echo "Bedrock_Build_Azure_Single_KeyVault: Test passed."
-        else
-          echo "Bedrock_Build_Azure_Single_KeyVault: Test failed."
-          exit 1
+        test2 = $?
+        echo "Test1: $test1 Test2: $test2"
+        # if [ $? -eq 0 ]
+        # then
+        #   echo "Bedrock_Build_Azure_Single_KeyVault: Test passed."
+        # else
+        #   echo "Bedrock_Build_Azure_Single_KeyVault: Test failed."
+        #   exit 1
       env:
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
         ARM_CLIENT_OBJECT_ID: $(ARM_CLIENT_OBJECT_ID)
@@ -242,7 +246,10 @@ stages:
         export public_key=$(cat id_rsa.pub)
         find $(modulePath)/cluster/environments/azure-multiple-clusters -type f -name '*.tf' -exec sed -i 's/github.com\/Microsoft\/bedrock\/cluster/..\/../g' {} \;
         go test -v -run TestIT_Bedrock_AzureMC_Test -timeout 99999s | tee TestIT_Bedrock_AzureMC_Test.log
+        test1 = $?
         terratest_log_parser -testlog TestIT_Bedrock_AzureMC_Test.log -outputdir mc_test_output
+        test2 = $?
+        echo "Test1: $test1 Test2: $test2"
 
       env:
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
